DROP TABLE IF EXISTS SUPERHERO;

CREATE TABLE SUPERHERO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  thumbnail VARCHAR(250) DEFAULT NULL
);
